### ISSUE TITLE
Failed to legalize operation 'memref.alloca'

### ISSUE THREAD

**Issue by not-jenni** [openxla/iree#10859] opened 2022-10-20 16:44 UTC
### What happened?

`error: failed to legalize operation 'memref.alloca' that was explicitly marked illegal`

Running iree-compile on an internal google tflite model results in errors for the VMVX backend. This is the MLIR snippet that reproduces the error:

```
  func.func @main(%arg0: tensor<256xi8>, %arg1: tensor<2xi32>, %arg2: tensor<2x32xi8>, %arg3: tensor<32xi32>, %arg4: tensor<32x32xi8>, %arg5: tensor<32xi32>, %arg6: tensor<32x3360xi8>, %arg7: tensor<?x3360xi8>) -> (tensor<?x2xi8>) {
    %0 = "tosa.fully_connected"(%arg7, %arg6, %arg5) {quantization_info = #tosa.conv_quant<input_zp = -128, weight_zp = 0>} : (tensor<?x3360xi8>, tensor<32x3360xi8>, tensor<32xi32>) -> tensor<?x32xi32>
    %1 = "tosa.rescale"(%0) {double_round = true, input_zp = 0 : i32, multiplier = [1101627623 : i32], output_zp = -128 : i32, per_channel = false, scale32 = true, shift = [36 : i32]} : (tensor<?x32xi32>) -> tensor<?x32xi8>
    %2 = "tosa.clamp"(%1) {max_fp = 0.000000e+00 : f32, max_int = 127 : i64, min_fp = 0.000000e+00 : f32, min_int = -128 : i64} : (tensor<?x32xi8>) -> tensor<?x32xi8>
    %3 = "tosa.fully_connected"(%2, %arg4, %arg3) {quantization_info = #tosa.conv_quant<input_zp = -128, weight_zp = 0>} : (tensor<?x32xi8>, tensor<32x32xi8>, tensor<32xi32>) -> tensor<?x32xi32>
    %4 = "tosa.rescale"(%3) {double_round = true, input_zp = 0 : i32, multiplier = [1255393165 : i32], output_zp = -128 : i32, per_channel = false, scale32 = true, shift = [35 : i32]} : (tensor<?x32xi32>) -> tensor<?x32xi8>
    %5 = "tosa.clamp"(%4) {max_fp = 0.000000e+00 : f32, max_int = 127 : i64, min_fp = 0.000000e+00 : f32, min_int = -128 : i64} : (tensor<?x32xi8>) -> tensor<?x32xi8>
    %6 = "tosa.fully_connected"(%5, %arg2, %arg1) {quantization_info = #tosa.conv_quant<input_zp = -128, weight_zp = 0>} : (tensor<?x32xi8>, tensor<2x32xi8>, tensor<2xi32>) -> tensor<?x2xi32>
    %7 = "tosa.rescale"(%6) {double_round = true, input_zp = 0 : i32, multiplier = [1879992488 : i32], output_zp = 44 : i32, per_channel = false, scale32 = true, shift = [39 : i32]} : (tensor<?x2xi32>) -> tensor<?x2xi8>
    %8 = "tosa.table"(%7, %arg0) : (tensor<?x2xi8>, tensor<256xi8>) -> tensor<?x2xi8>
    return %8 : tensor<?x2xi8>
  }
```

Full error output:
https://gist.github.com/not-jenni/8d49048a65200dfa2a5ba19ae128a2ec

### Steps to reproduce your issue

1. Download the mlir snippet
2. Run `./iree-compile  -iree-input-type=tosa -iree-hal-target-backends=vmvx sample.mlir`

### What component(s) does this issue relate to?

Compiler

### Version information

https://github.com/iree-org/iree/commit/108c64a2bbdb3907969421f906c1c4437db6a356

### Additional context

This model failure was pointed out by @lundong

**Comment by not-jenni** [comment] 2022-11-15 19:17
@ScottTodd Are you available to please help triage this when you get a chance?  Thank you!

**Comment by ScottTodd** [comment] 2022-11-15 19:26
I haven't been tracking the status of vmvx and/or memref closely enough to help much with this, sorry. Does that program compile correctly for any other backends?

**Comment by hanhanW** [comment] 2022-11-28 22:31
This is because

1.) it is dynamic case
2.) this is a quantized model.

The op is not vectorized because there are dynamic dims. If they are not vectorized, we'll need bufferization to reuse dest buffer for all of the operations. However, we can not update the result of matmul in-place because of (2). I.e., the element types mismatch. In this context, we allocate a stack buffer, which is not allowed in VMVX backend.

There are couple ways to fix it.

a.) Tile dynamic dims with size `1`, so we can always vectorize it.
b.) Move the dispatch to peeling or padding approach.

(a) is a simple workaround, (b) needs more work and we probably don't have cycles.

IR from log:

```
func.func @main_dispatch_2_generic_Dx32() {
  %c0_i32 = arith.constant 0 : i32
  %c-128_i32 = arith.constant -128 : i32
  %c1101627623_i32 = arith.constant 1101627623 : i32
  %c36_i8 = arith.constant 36 : i8
  %c127_i32 = arith.constant 127 : i32
  %c-128_i8 = arith.constant -128 : i8
  %c127_i8 = arith.constant 127 : i8
  %c108800 = arith.constant 108800 : index
  %c107520 = arith.constant 107520 : index
  %c0 = arith.constant 0 : index
  %0 = hal.interface.constant.load[0] : i32
  %1 = arith.index_castui %0 : i32 to index
  %2 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:tensor<3360x32xi8>>
  %3 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:tensor<32xi32>>
  %4 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) offset(%c107520) alignment(64) : !flow.dispatch.tensor<readonly:tensor<32xi32>>
  %5 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) offset(%c0) alignment(64) : !flow.dispatch.tensor<readonly:tensor<?x3360xi8>>{%1}
  %6 = hal.interface.binding.subspan set(0) binding(3) type(storage_buffer) offset(%c108800) alignment(64) : !flow.dispatch.tensor<writeonly:tensor<?x32xi8>>{%1}
  %7 = flow.dispatch.tensor.load %5, offsets = [0, 0], sizes = [%1, 3360], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<?x3360xi8>>{%1} -> tensor<?x3360xi8>
  %8 = flow.dispatch.tensor.load %2, offsets = [0, 0], sizes = [3360, 32], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<3360x32xi8>> -> tensor<3360x32xi8>
  %9 = flow.dispatch.tensor.load %3, offsets = [0], sizes = [32], strides = [1] : !flow.dispatch.tensor<readonly:tensor<32xi32>> -> tensor<32xi32>
  %10 = flow.dispatch.tensor.load %4, offsets = [0], sizes = [32], strides = [1] : !flow.dispatch.tensor<readonly:tensor<32xi32>> -> tensor<32xi32>
  %11 = tensor.empty(%1) : tensor<?x32xi8>
  %12 = tensor.empty(%1) : tensor<?x32xi32>
  %13 = linalg.fill ins(%c0_i32 : i32) outs(%12 : tensor<?x32xi32>) -> tensor<?x32xi32>
  %14 = linalg.matmul ins(%7, %8 : tensor<?x3360xi8>, tensor<3360x32xi8>) outs(%13 : tensor<?x32xi32>) -> tensor<?x32xi32>
  %15 = linalg.generic {indexing_maps = [affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0, d1)>, affine_map<(d0, d1) -> (d1)>, affine_map<(d0, d1) -> (d0, d1)>], iterator_types = ["parallel", "parallel"]} ins(%9, %14, %10 : tensor<32xi32>, tensor<?x32xi32>, tensor<32xi32>) outs(%11 : tensor<?x32xi8>) {
  ^bb0(%in: i32, %in_0: i32, %in_1: i32, %out: i8):
    %16 = arith.muli %in_1, %c-128_i32 : i32
    %17 = arith.subi %in_0, %16 : i32
    %18 = arith.addi %in, %17 : i32
    %19 = "tosa.apply_scale"(%18, %c1101627623_i32, %c36_i8) {double_round = true} : (i32, i32, i8) -> i32
    %20 = arith.addi %19, %c-128_i32 : i32
    %21 = arith.cmpi slt, %20, %c-128_i32 : i32
    %22 = arith.select %21, %c-128_i32, %20 : i32
    %23 = arith.cmpi sgt, %20, %c127_i32 : i32
    %24 = arith.select %23, %c127_i32, %22 : i32
    %25 = arith.trunci %24 : i32 to i8
    %26 = arith.cmpi slt, %25, %c-128_i8 : i8
    %27 = arith.select %26, %c-128_i8, %25 : i8
    %28 = arith.cmpi sgt, %25, %c127_i8 : i8
    %29 = arith.select %28, %c127_i8, %27 : i8
    linalg.yield %29 : i8
  } -> tensor<?x32xi8>
  flow.dispatch.tensor.store %15, %6, offsets = [0, 0], sizes = [%1, 32], strides = [1, 1] : tensor<?x32xi8> -> !flow.dispatch.tensor<writeonly:tensor<?x32xi8>>{%1}
  return
}
```

**Comment by lundong** [comment] 2022-11-30 19:24
@hanhanW Thanks very much for the fix and it does work. I just found another scenario (in which microkernel is enabled) that also results in the error "Failed to legalize operation 'memref.alloca". Could you please take a look at it? Thanks.

Steps to reproduce your issue:
1. Download model.mlir from another issue: https://github.com/iree-org/iree/issues/10855
2. Run path/to/iree-compile -iree-input-type=tosa -iree-hal-target-backends=vmvx -iree-vmvx-enable-microkernels path/to/model.mlir
3. See error
failed to legalize operation 'memref.alloca' that was explicitly marked illegal ...

**Comment by lundong** [comment] 2023-02-09 18:23
@not-jenni  I can confirm this issue has been fixed by https://github.com/iree-org/iree/pull/12099. So this issue can be closed.

**Closed** 2023-03-27 08:13 UTC
Labels: bug 🐞, codegen/vmvx
