### ISSUE TITLE
Collect metrics for miscellaneous IREE system states

### ISSUE THREAD

**Issue by antiagainst** [openxla/iree#6161] opened 2021-06-09 17:30 UTC
Right now the benchmark pipeline only supports model benchmarks, with basically the following scheme:

```
<input-model> [<model-tags>] (<model-source>) <benchmark-mode-tags>
with <iree-driver> @ <device-name> (<target-arch>)
```

We need to increase the metrics collection to include various IREE system states and track them in the dashboard like model benchmarks. 

This issue is for collecting such miscellaneous metrics, and trying to define a category and naming scheme for them for consistency.

**Comment by antiagainst** [comment] 2021-06-09 17:34
Some initial candidates to be refined:

* Compiled VMFB size
* IREE runtime binary size
* IREE system initialization time

Also initial thoughts from @ScottTodd:

> * model compilation time
> * peak runtime memory use
> * certain pass statistics
> * program analyses (e.g. number of synchronization points)

**Comment by ScottTodd** [comment] 2021-09-03 15:47
Pass statistics ([sample output](https://gist.github.com/ScottTodd/0af73e4e5099ccb97f9e2e4137092867)) can be extracted with

``` bash
# build with CMake in Debug or RelWithDebInfo + `-DLLVM_FORCE_ENABLE_STATS=ON`

iree-translate \
  ${MODEL_PATH} (flags like -iree-input-type=mhlo) \
  -pass-statistics \
  -o /dev/null \
  2> ${MODEL}_statistics.txt

# Extract number of dispatches after FusionOfTensorOps + DispatchLinalgOnTensors
cat ${MODEL}_statistics.txt | grep "number of dispatches" | sed -E 's/.* ([0-9]+) number.*/\1/'
# Extract number of unique executables after DeduplicateExecutables
cat ${MODEL}_statistics.txt | grep "unique executable" | sed -E 's/.* ([0-9]+) unique.*/\1/'
```

For [bert_encoder_unrolled_fake_weights.mlir](https://github.com/google/iree/blob/main/iree/test/e2e/models/bert_encoder_unrolled_fake_weights.mlir) there are currently 969 dispatches and 28 unique executables. The number of dispatches is a useful codegen metric tracking how much code is getting fused, and tracking that would make regressions like https://github.com/google/iree/pull/6648 easier to spot.

We can add more statistics with https://github.com/google/iree/issues/1409. Number of host round trips will be useful for flow->streams->hal.

---

https://github.com/google/iree/pull/6868 added the `--print_statistics` flag for `iree-run-module`, with output like

```
[[ iree_hal_allocator_t memory statistics ]]
  HOST_LOCAL:            0b peak /            0b allocated /            0b freed /            0b live
DEVICE_LOCAL:    106340864b peak /    106340864b allocated /    106340864b freed /            0b live
```
which will give an accurate report for memory usage even for models with dynamic behavior.

**Comment by allieculp** [comment] 2023-04-10 21:41
Sending to backlog due to the date of the issue - please reprioritize if needed.

**Comment by ScottTodd** [comment] 2023-04-10 21:47
Is there anything still to do here, or can that be tracked in other issues? We are measuring some metrics (but more would be nice).

**Comment by pzread** [comment] 2023-05-08 16:20
The benchmark tools can now collect memory usages (https://github.com/openxla/iree/pull/13325), compilation time, dispatch sizes, and will include the numbers of dispatches soon. I think in general we have a schema to collect multiple metrics, so we can close this one. (And for sure more metrics will be added later).

**Closed by pzread** 2023-05-08 16:20 UTC
Labels: infrastructure, infrastructure/benchmark
