### ISSUE TITLE
iree_tf_compiler/TF can be replaced with TensorFlow functionality

### ISSUE THREAD

**Issue by matthiaskramm** [openxla/iree#10849] opened 2022-10-19 19:32 UTC
TensorFlow now has [code that lowers savedmodels to stablehlo + ml_program](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/utils/mlprogram_util.h#L31) ([pass pipeline](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/transforms/mlprogram.cc#L33)). This aims to be equivalent to (and is, in fact, heavily inspired by) the IREE code under [iree_tf_compiler/TF](https://github.com/iree-org/iree/tree/main/integrations/tensorflow/iree_tf_compiler/TF).

At the very least, several pass implementations can likely be deleted (e.g. LowerGlobalTensors and StripMetadata), but possibly the entire [iree-import-tf](https://github.com/iree-org/iree/blob/main/integrations/tensorflow/iree_tf_compiler/iree-import-tf-main.cpp) binary can be replaced with something that instead calls the TensorFlow binaries, in the following way:

```
tf-mlir-translate --savedmodel-objectgraph-to-mlir /path/to/saved_model/ > savedmodel.mlir
tf-opt -tf-lower-to-mlprogram-and-hlo savedmodel.mlir
```

**Comment by jpienaar** [comment] 2022-10-19 20:57
Thanks for the update! I was just about to ask earlier today, glad to be beaten to the punch :) OOC do those tools make it to any of the pip packages?

**Comment by matthiaskramm** [comment] 2022-10-19 21:56
> OOC do those tools make it to any of the pip packages?

I don't see them in the `tensorflow` pip package. Which probably makes sense, they're not used much outside of unit tests.

I think you can access the passes / pipelines from Python, though?

**Comment by matthiaskramm** [comment] 2022-10-20 20:05
We can also (maybe, if the maintainers let us) add ml_program+stablehlo output capability to savedmodel_cli. The latter _does_ get shipped with tensorflow pip.

**Comment by jpienaar** [comment] 2022-10-20 20:28
Yes couple of options, was just prefetching some ideas. It'll unfortunately be a bit of time before we get to integrating here... Well I want to try, but should decrease stack first before adding on :-)

**Comment by stellaraccident** [comment] 2022-10-21 01:13
This is great progress - thank you Matthias!

I'm fairly motivated to kill iree-import-tf. It would be great to have proper python apis, but if we got equivalent functionality into savedmodel_cli, that would allow for an immediate transition to use that behind iree's python apis, and I expect we could then kill the importer completely. Even if transitional, that could be a good way to go...

**Comment by jpienaar** [comment] 2022-10-21 17:03
(adding Natasha to track & help with switch post Python APIs/savedmodel_cli usability)

**Comment by matthiaskramm** [comment] 2022-10-21 19:11
Once the tensorflow pip package is recent, looks like we can just do

```
from tensorflow.python import pywrap_mlir

saved_model = pywrap_mlir.experimental_convert_saved_model_to_mlir(
    "/path/to/saved/model", [], show_debug_info=False)
result = pywrap_mlir.experimental_run_pass_pipeline(
    saved_model, "tf-lower-to-mlprogram-and-hlo", show_debug_info=False)
```

(There's some string serialization happening here, but it doesn't seem like there's a way around that given that tensorflow statically links against its own MLIR.)

Will update this thread once this is good to go.

**Comment by matthiaskramm** [comment] 2022-11-19 00:09
Update: With tf-nightly, the code given in the previous comment works now. However, I've seen it trigger a bug (segfault) in TF's pattern matcher, for some models. Will post an update once that issue is resolved.

**Comment by stellaraccident** [comment] 2022-11-19 02:34
Thank you Matthias!

**Comment by matthiaskramm** [comment] 2022-12-05 21:32
This should be good to go now (using tf-nightly).

**Comment by jpienaar** [comment] 2022-12-06 16:32
Seems to be textual/debugging format still rather than bytecode but using StableHLO (conversion to StableHLO at end of pipeline from MHLO, so should be input here).

**Comment by jpienaar** [comment] 2022-12-06 16:37
And we'd need to encode as bytecode TF side/part of nightly release.

**Comment by christopherbate** [comment] 2022-12-06 18:10
This is a really interesting feature that I'm sure non-IREE users (like myself) would be interested in as well. I was looking at forking just `iree_tf_compiler` as a way of getting a tool to get HLO just from a saved model.

I created this test that shows a more complete example. It reuses some of the code from the [TF SaveModel tutorial](https://www.tensorflow.org/guide/saved_model), but also exports the backprop program. I added conversion back to HLO for kicks.

```python
""" Example showing how to turn a SavedModel into an MLIR module that contains
only StableHlo/HLO dialect + upstream MLIR dialects.
"""
import tensorflow as tf
from tensorflow.python import pywrap_mlir
from pathlib import Path

saved_model_path = "./test_model"

# ---------------------------------------------------------------
# Create a simple test model
# ---------------------------------------------------------------


class CustomModule(tf.Module):
  def __init__(self):
    super(CustomModule, self).__init__()
    self.v = tf.Variable(1.5)

  @tf.function
  def __call__(self, x):
    print("tracing with", x)
    return x * self.v

  @tf.function
  def train_step(self, input):
    with tf.GradientTape() as tape:
      loss = (10. - self(input)) ** 2
    variables = tape.watched_variables()
    grads = tape.gradient(loss, variables)
    print(grads)
    return list(grads) + [loss]


module = CustomModule()
infer_call = module.__call__.get_concrete_function(
  tf.TensorSpec((None, 10, 10, 10), tf.float32))
train_call = module.train_step.get_concrete_function(
  tf.TensorSpec((None, 10, 10, 10), tf.float32))
tf.saved_model.save(module, "./test_model",
                    signatures={"infer": infer_call, "train": train_call})


# ---------------------------------------------------------------
# Convert saved model to Stablehlo + upstream MLIR ops
# ---------------------------------------------------------------

def convert_to_hlo(model_path: str, use_stablehlo=True):
  result = pywrap_mlir.experimental_convert_saved_model_to_mlir(
      saved_model_path, "", show_debug_info=False)
  pipeline = ["tf-lower-to-mlprogram-and-hlo"]
  if not use_stablehlo:
    pipeline.append("stablehlo-legalize-to-hlo")
  result = pywrap_mlir.experimental_run_pass_pipeline(
      result, ",".join(pipeline), show_debug_info=False)
  return result


Path("test_model.stablehlo.mlir").write_text(
  convert_to_hlo("./test_model", True))
Path("test_model.hlo.mlir").write_text(convert_to_hlo("./test_model", False))
```



I currently have signature of shape to be dynamic in the first dimension. In this case, the backprop function will still contain some tf ops including things like `tf.Sum`. It seems  to be do to presence of `tf.BroadcastGradientArgs`.

When shapes are static all TF opeations are gone.

It would be awesome to be able to pass MLIR printer args as well like `mlir-elide-elementsattrs-if-larger=32` and `mlir-print-local-scope`

**Comment by jpienaar** [comment] 2022-12-06 18:48
> When shapes are static all TF opeations are gone.

Yeah this may be the same gap mentioned above (dynamic shape support paths diverged a bit), so this is great example.

> It would be awesome to be able to pass MLIR printer args as well like mlir-elide-elementsattrs-if-larger=32 and mlir-print-local-scope

Agreed, I think we could do it with wrapper (we are parsing strings quite a bit here ... but I think for export path this may be OK starting point).

**Comment by jpienaar** [comment] 2022-12-08 16:11
Sent out bytecode writing for review TF side.

@matthiaskramm could you follow up on missing legalization in this example with bridge team?

**Comment by matthiaskramm** [comment] 2022-12-08 20:10
Thanks for sending out the bytecode change, Jacques! Beat me to the punch. :)

The dynamic shape issue is known, and being worked on. Not sure about timelines, though. For now, trying to make shapes static whenever possible is a good idea.

**Comment by stellaraccident** [comment] 2022-12-08 20:57
I propose that it is now time to disable TF dynamic shape tests. We have the coverage through other channels, and I believe we need to re-evaluate requirements and design for the TF side in light of strong work on the Jax/PyTorch/TFLite side and the actual needs of a compiler at this level.

**Comment by dellis23** [comment] 2023-02-13 19:45
@christopherbate did you do anything special to get the `tf-lower-to-mlprogram-and-hlo` pipeline pass registered? I'm getting the following error when I try to run your code:

```python
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid pass_pipeline: MLIR Textual PassPipeline Parser:1:1: error: 'tf-lower-to-mlprogram-and-hlo' does not refer to a registered pass or pass pipeline
tf-lower-to-mlprogram-and-hlo
```

It looks like the [pipeline name is correct](https://github.com/tensorflow/tensorflow/blob/b2f15b8923653bc4480c683c1c184080289a38fa/tensorflow/compiler/mlir/tensorflow/utils/mlprogram_util.cc#L37); I'm not sure how to get this code to run though (assuming it isn't).

**Comment by pjannaty** [comment] 2023-02-14 03:46
@dellis23 the TF 2.11 release does not register the pass [ tensorflow::RegisterMlProgramPasses()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/python/mlir.cc#L98). You can use the nightlies however.

**Comment by dellis23** [comment] 2023-02-14 16:28
I have a rudimentary version working, but the exposed public names using the tensorflow API are not consistent with what we're producing now.

As an example, consider the following model:

```python
class MyModel(tf.Module):

  @tf.function
  def train(self, x):
    #...
```

Using the current `iree-import-tf` tool, I get back MLIR with a public `train` function and a private `__inference_train_250` function; I'm able to run `train` using `iree-run-module` just fine.

Using `experimental_convert_saved_model_to_mlir`, the returned MLIR has the nice `train` name stripped entirely, leaving only `__inference_train_250`. I'm able to run that with IREE, but I think this is pretty obviously a non-starter from a usability and regression perspective.

(As a side note, I've dug through saved model internals for years and the contradiction in the name `__inference_train_250` is somehow still humorous to me.)

**Comment by dellis23** [comment] 2023-02-14 17:02
Filed https://github.com/tensorflow/tensorflow/issues/59685

**Comment by bhack** [comment] 2023-02-22 15:25
When this is solved do you think that we could modify this section of the image in the Readme?

![immagine](https://user-images.githubusercontent.com/1710528/220668838-2288164c-03fd-49c2-9340-ebe40a16b04a.png)

**Comment by jpienaar** [comment] 2023-02-22 15:45
> When this is solved do you think that we could modify this section of the image in the Readme?
> 

I think it can be updated but for other reasons. There is still an input and preprocessing to useful state for IREE/OpenXLA that happens there. This moved some of what was in the TF specific import upstream (but the same is true for JAX, TOSA and PyTorch independent of this), but there is still some massaging required before it is in desired input format. It can be made more explicit where some of these importers live now.

**Comment by bhack** [comment] 2023-02-22 15:54
Mhh... so what is the relationship between the Importers block and the API in https://github.com/openxla/openxla-pjrt-plugin?

Isn't the plugin ingesting directly StableHLO program?

**Comment by jpienaar** [comment] 2023-02-22 16:11
Plugin and IREE are different things. While there is a plugin whose interfaces are implemented (and we are promoting that as/evolving it for framework integration), that is not the only way to use IREE. StableHLO is a supported opset but not an exclusive input one (that's true for the plugin too though).

**Comment by bhack** [comment] 2023-02-22 21:08
> Plugin and IREE are different things. While there is a plugin whose interfaces are implemented (and we are promoting that as/evolving it for framework integration), that is not the only way to use IREE. StableHLO is a supported opset but not an exclusive input one (that's true for the plugin too though).

Thank you for the clarification, I've supposed that StableHLO was the only unified entry-point in the roadmap.

Does it makes sense to upgrade the welcome image at least if it isn't generically represented only by IREE importers blocks? 

e.g. is StableHLO  an IREE importer? Is the standard plugin API an IREE importer?

**Comment by benvanik** [comment] 2023-02-22 21:11
I'm not quite sure of the distinction you're trying to make. IREE often requires or handles additional preprocessing on top of whatever the input format is - that code generally lives in IREE, and is an "IREE importer for a particular input representation" - see https://github.com/openxla/iree/tree/main/compiler/src/iree/compiler/InputConversion.

(note that you can have out-of-tree importers too - the common import path is always run, though, and if you can get on one of those things are handled for you - but otherwise a tool outside of IREE could include the IREE dialects and convert to IREE's public import dialect if it wanted: https://github.com/openxla/iree/blob/main/llvm-external-projects/iree-dialects/include/iree-dialects/Dialect/Input/InputOps.td)

**Comment by bhack** [comment] 2023-02-22 21:20
Ok I suppose that this means that also for StableHLO we will have just another preprocessor/importer.

**Comment by benvanik** [comment] 2023-02-22 21:23
Ideally we'd replace the MHLO path with StableHLO when it's ready.

**Comment by dellis23** [comment] 2023-04-07 14:49
Closed via https://github.com/openxla/iree/pull/12758

**Comment by dellis23** [comment] 2023-04-07 15:29
https://github.com/openxla/iree/pull/12972

**Comment by allieculp** [comment] 2023-04-27 20:40
@dellis23 Is this closed?

**Comment by dellis23** [comment] 2023-04-27 20:47
I'm not sure of the current state of this.  I'm no longer working on it, but I forgot to change the assignee field.

**Comment by ScottTodd** [comment] 2023-10-05 20:32
I'm pretty sure this issue as filed is fixed now, though there are some related threads in the discussion here. How about we file new issues/discussions if there are still areas to work on?

**Closed by ScottTodd** 2023-10-05 20:32 UTC
Labels: integrations/tensorflow
