### ISSUE TITLE
compilation error for VAE encoder 

### ISSUE THREAD

**Issue by PhaneeshB** [openxla/iree#11982] opened 2023-01-27 07:03 UTC
### What happened?

When compiling VAE encode iree-compile fails with the following error:

```
  File "C:\P\SHARK\shark.venv\lib\site-packages\iree\compiler\tools\binaries.py", line 196, in invoke_immediate
    raise CompilerToolError(process)
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
<eval_with_key>.3:651:14: error: failed to legalize operation 'arith.constant'
<eval_with_key>.3:651:14: error: Failures have been detected while processing an MLIR pass pipeline
<eval_with_key>.3:651:14: note: Pipeline failed while executing [`mlir::iree_compiler::IREE::HAL::TranslateExecutablesPass` on 'hal.executable' operation: @forward_dispatch_167, `mlir::iree_compiler::IREE::HAL::TranslateTargetExecutableVariantsPass` on 'hal.executable.variant' operation: @vulkan_spirv_fb, `ConvertToSPIRV` on 'builtin.module' operation]: reproducer generated at `./iree_save_temps\core-reproducer.mlir`
<eval_with_key>.3:651:14: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.6, [Shader, Float64, Float16, Int64, Int16, Int8, StorageBuffer16BitAccess, StorageUniform16, StoragePushConstant16, StorageBuffer8BitAccess, UniformAndStorageBuffer8BitAccess, StoragePushConstant8, GroupNonUniform, GroupNonUniformVote, GroupNonUniformArithmetic, GroupNonUniformBallot, GroupNonUniformShuffle, GroupNonUniformShuffleRelative, GroupNonUniformClustered, GroupNonUniformQuad, VariablePointers, VariablePointersStorageBuffer, CooperativeMatrixNV], [SPV_KHR_16bit_storage, SPV_KHR_8bit_storage, SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers, SPV_NV_cooperative_matrix]>, api=Vulkan, AMD:DiscreteGPU, #spirv.resource_limits<max_compute_shared_memory_size = 65536, max_compute_workgroup_invocations = 1024, max_compute_workgroup_size = [1024, 1024, 1024], subgroup_size = 64, min_subgroup_size = 32, max_subgroup_size = 64, cooperative_matrix_properties_nv = [#spirv.coop_matrix_props<m_size = 16, n_size = 16, k_size = 16, a_type = f16, b_type = f16, c_type = f16, result_type = f16, scope = <Subgroup>>]>>}>
<eval_with_key>.3:651:14: error: failed to serialize executables

```

### Steps to reproduce your issue

command 
```
./iree-compile.exe \
--iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan \
--mlir-print-debuginfo --mlir-print-op-on-diagnostic=false 
--mlir-pass-pipeline-crash-reproducer=./iree_save_temps\core-reproducer.mlir --iree-llvm-target-cpu-features=host 
--iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna3-7900-windows
```

vulkan_target_env used:
```
--iree-vulkan-target-env=#vk.target_env<v1.3, r(120), [VK_KHR_16bit_storage, VK_KHR_8bit_storage, VK_KHR_shader_float16_int8, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_variable_pointers, VK_EXT_subgroup_size_control, VK_NV_cooperative_matrix], AMD:DiscreteGPU, #vk.caps< maxComputeSharedMemorySize = 65536, maxComputeWorkGroupInvocations = 1024, maxComputeWorkGroupSize = dense<[1024, 1024, 1024]>: vector<3xi32>, subgroupSize = 64, subgroupFeatures = 255: i32, minSubgroupSize = 32, maxSubgroupSize = 64, shaderFloat16 = unit, shaderFloat64 = unit, shaderInt8 = unit, shaderInt16 = unit, shaderInt64 = unit, storageBuffer16BitAccess = unit, storagePushConstant16 = unit, uniformAndStorageBuffer16BitAccess = unit, storageBuffer8BitAccess = unit, storagePushConstant8 = unit, uniformAndStorageBuffer8BitAccess = unit, variablePointers = unit, variablePointersStorageBuffer = unit, cooperativeMatrixPropertiesNV = [#vk.coop_matrix_props<mSize = 16, nSize = 16, kSize = 16, aType = f16, bType = f16, cType = f16, resultType = f16, scope = #vk.scope<Subgroup>>] >>
```

[input.mlir](https://storage.googleapis.com/shark-public/phaneesh/vae_encode_error/core-input.mlir)
[reproducer.mlir](https://storage.googleapis.com/shark-public/phaneesh/vae_encode_error/core-reproducer.mlir)

### What component(s) does this issue relate to?

Compiler

**Comment by antiagainst** [comment] 2023-01-30 18:02
I cannot reproduce the issue at b14aaf486. Please double check whether this is still a problem.

**Comment by antiagainst** [comment] 2023-03-21 21:05
Not hearing back for quite some time. So closing this for now.

**Closed by antiagainst** 2023-03-21 21:05 UTC
Labels: bug 🐞
