### ISSUE TITLE
`iree-tf-import` stack traces are an eyesore

### ISSUE THREAD

**Issue by stellaraccident** [openxla/iree#5295] opened 2021-04-02 04:31 UTC
On a compiler error, if the saved model was saved with debug information (i.e. `tf.saved_model.save(..., options=tf.saved_model.SaveOptions(save_debug_info=True))`) we do get stack traces with original source locations, but they print horrendously using the default diagnostic printer (i.e. `callsite(...)` tags all run together on one line. We should find/make/use a pretty standard diagnostic printer in all of our compiler tools.

**Comment by GMNGeoffrey** [comment] 2021-04-02 16:15
Could you provide an example log? I think this is specific to the Python integration, right? The issue is that the source locations from Python don't print nicely with the standard diagnostic printer?

**Comment by stellaraccident** [comment] 2021-04-05 19:45
The exact case I'm looking at is a private model, and we do try to keep in tree tests from having compiler errors, so no :)

It is printing basically as one long line of `loc(.... 2 lines of huge file path...:{line}:{col})` all run together with one for each level of the python stack trace. I'm going to do some ad-hoc formatting and make it better. Then see if that is something to make more common. I don't think there is really a "great" option given how TensorFlow represents debug info, but "better" should be attainable.

**Comment by silvasean** [comment] 2021-04-15 19:42
It doesn't fully help, but `-mlir-pretty-debuginfo` at least gives one-line-per-callsite.

Also, some thoughts:

The ugliness here is the result of 2 things:

1) TF capturing the entire Python stack trace at the callsite -- arguably correct and good, but not the best experience for users. As a developer that cares about internals, I've found myself using various parts of the stack trace, but perhaps users only care about the top entry, or at least the the stuff that is not "internal to tensorflow", which we could heuristically identify by whehter the path contains `tensorflow/python/` or some other special string.

2) Unreasonably long bazel paths usually.

River mentioned that this was a real usability issue for folks he was talking to, so if this is becoming a problem, we can write a pass "TF adjust locations" which:
1) strips of everything up to the last bazel workspace root in the path (or something like that).
2) trims down those callsite locations such that only paths that don't contain `tensorflow/python/` are retained.

**Comment by stellaraccident** [comment] 2021-04-16 03:53
Having tried to fix this upstream at various points in the past by being smarter about filtering, etc, I think I am in favor of the "TF adjust locations" pass, probably with a default flag that strips it to one heuristically determined entry. Possibly there is some way to model this so that only the "best" callsite is stored in a way that the default location formatters use (which are also not active here) but all are preserved. This would allow us to have flags at any stage of the tooling to "dump everything" but not bother most people with that.

**Comment by stellaraccident** [comment] 2021-04-17 00:37
This is so tangled. I think I have an approach in my head to simplify it, though.

**Comment by alliemartens** [comment] 2022-07-13 16:28
@stellaraccident Old issue alert! Still active?

**Comment by aaron-schneider** [comment] 2023-04-17 23:34
Ho there! This bug hasn't been updated in a long time. Good intentions and all, but we're moving this to the backlog. Feel free to bring it back if you think there's a reasonable chance it'll get worked on in the next 6mo!

**Comment by GMNGeoffrey** [comment] 2023-04-17 23:38
Well iree-import-tf has been removed, so I think safe to close this entirely.

**Closed by GMNGeoffrey** 2023-04-17 23:38 UTC
Labels: help wanted, integrations/tensorflow, quality of life 😊
