### ISSUE TITLE
[spirv] PyTorch SqueezeNet returns NaN values on Apple M GPUs

### ISSUE THREAD

**Issue by PhaneeshB** [openxla/iree#9972] opened 2022-08-01 12:27 UTC
### What happened?

On comparing the results obtained from PyTorch with SHARK results, it was found that the difference in values is more than the acceptable tolerance range.
Here's the error shown:

```
>       assert True == compare_tensors(act_out, results)
E       assert True == False
E        +  where False = compare_tensors((array([3.14428282e+00, 3.22302604e+00, 5.40687680e-01, 3.73111218e-01,\n       2.96625471e+00, 3.04594326e+00, 2.91952753e+00, 4.42610502e+00,\n       2.66420364e+00, 2.83965898e+00, 4.10072058e-01, 1.35130215e+00,\n       1.07692492e+00, 1.08049130e+00, 2.76354003e+00, 2.86041617e+00,\n       3.06428403e-01, 4.17078924e+00, 5.51575565e+00, 1.02667892e+00,\n       5.12584746e-01, 2.35961628e+00, 1.41441464e+00, 3.29061079e+00,\n       2.04629946e+00, 7.02877939e-01, 1.68239105e+00, 3.04431415e+00,\n       8.57822418e-01, 5.26562274e-01, 2.76680160e+00, 2.72498679e+00,\n       1.29817390e+00, 5.49149394e-01, 1.79637933e+00, 2.11042786e+00,\n       2.44551325e+00, 1.70634091e+00, 1.69635284e+00, 5.87331057e+00,\n       4.19273710e+00, 2.66559529e+00, 3.76101089e+00, 1.75203526e+00,\n       2.18577743e+00, 1.99968684e+00, 5.36900043e+00, 3.39813018e+00,\n       3.81504679e+00, 1.84688628e+00, 3.50770640e+00, 7.81702340e-01,\n       1.38481939e+00, 9.08863962e-01, 2.41946769e+00, 2.93652892e+00,\n       2.32596231e+00, 2.15748143e+00, 2.26216221e+00, 1.90700102e+00,\n       2.15615749e+00, 2.54449224e+00, 1.83004308e+00, 1.26655436e+00,\n       2.02197266e+00, 2.36331606e+00, 1.67235494e+00, 3.7545...02e-01, 4.66123670e-01, 4.09210891e-01,\n       4.88783240e-01, 2.75332975e+00, 1.37207210e+00, 3.12985826e+00,\n       4.97734576e-01, 2.43807301e-01, 3.38988900e-01, 4.75265443e-01,\n       2.53791273e-01, 9.19587612e-01, 1.21111345e+00, 2.42586327e+00,\n       2.54854560e+00, 1.02105355e+00, 2.42882323e+00, 3.11654210e+00,\n       8.64926398e-01, 2.00554276e+00, 2.69069552e+00, 4.15229607e+00,\n       4.04710412e-01, 2.96282506e+00, 4.38517714e+00, 1.90314874e-02,\n       1.45576978e+00, 6.36449978e-02, 4.25690860e-01, 5.44690132e-01,\n       5.54477982e-02, 4.07951325e-02, 2.68874931e+00, 1.67620349e+00,\n       1.65641320e+00, 1.17499053e+00, 1.40869200e+00, 6.23076725e+00,\n       3.09542513e+00, 3.90765047e+00, 7.54088283e-01, 5.20562983e+00,\n       3.53361797e+00, 3.47739315e+00, 2.69032288e+00, 2.26547194e+00,\n       5.22517490e+00, 7.45811701e+00, 3.47911000e+00, 1.32941628e+00,\n       7.02118874e+00, 3.94310141e+00, 2.01791620e+00, 3.59294534e+00,\n       1.18769050e+00, 5.56126177e-01, 2.83776569e+00, 1.02769351e+00,\n       1.14343178e+00, 3.32554430e-01, 2.73019642e-01, 3.08494091e-01,\n       9.85914171e-01, 1.52028227e+00, 2.94635940e+00, 2.59162021e+00],\n      dtype=float32),), 
array([[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, na...an, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,\n        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],\n      dtype=float32))
```

### Steps to reproduce your issue

This script can be used to reproduce the issue:

```
from shark.shark_inference import SharkInference
from shark.shark_downloader import download_torch_model
from tank.model_utils import compare_tensors
import numpy as np

if __name__ == "__main__":

    model_mlir, func_name, input, act_out = download_torch_model(
        "squeezenet1_0", "True"
    )

    shark_module = SharkInference(
        model_mlir,
        func_name,
        device="vulkan",
        mlir_dialect="linalg",
        is_benchmark=False,
    )

    shark_module.compile()
    results = shark_module.forward(input)
    print(results)
    assert True == compare_tensors(act_out, results)

```

Link to `compare_tensors(t1, t2)` : https://github.com/nod-ai/SHARK/blob/d556c0d6ef8f69b32bc3b2d28165345dd2faf403/tank/model_utils.py#L99

### Additional context

1. VulkanSDK needs to be installed on the system.
2. IREE built from source code with Vulkan flags enabled is also able to reproduce the error.
3. To execute with m1-moltenvk-macos target triple on Apple M2, please make the following change in the SHARK source code
file : https://github.com/nod-ai/SHARK/blob/d556c0d6ef8f69b32bc3b2d28165345dd2faf403/shark/iree_utils/vulkan_utils.py#L23
replace : `if vulkan_device == "M1":`
with : `if vulkan_device == "M1" or vulkan_device == "M2":`

**Comment by stellaraccident** [comment] 2022-08-01 15:46
Does this only repro on the M2? I don't think that anyone in the iree core team has that hardware.

**Comment by powderluv** [comment] 2022-08-02 18:09
This happens on M1 too: https://github.com/nod-ai/SHARK/runs/7636875382?check_suite_focus=true

All the following models fail on M1 Vulkan but pass on Linux Vulkan

```
=========================== short test summary info ============================
FAILED tank/convbert-base-turkish-cased_tf/convbert-base-turkish-cased_tf_test.py::ConvBertModuleTest::test_module_static_vulkan
FAILED tank/pytorch/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_test.py::MiniLMModuleTest::test_module_dynamic_vulkan
FAILED tank/pytorch/MiniLM-L12-H384-uncased/MiniLM-L12-H384-uncased_test.py::MiniLMModuleTest::test_module_static_vulkan
FAILED tank/pytorch/alexnet/alexnet_test.py::AlexnetModuleTest::test_module_static_vulkan
FAILED tank/pytorch/bert-base-uncased/bert-base-uncased_test.py::BertBaseUncasedModuleTest::test_module_dynamic_vulkan
FAILED tank/pytorch/bert-base-uncased/bert-base-uncased_test.py::BertBaseUncasedModuleTest::test_module_static_vulkan
FAILED tank/pytorch/mobilebert-uncased/mobilebert-uncased_test.py::MobileBertModuleTest::test_module_dynamic_vulkan
FAILED tank/pytorch/mobilebert-uncased/mobilebert-uncased_test.py::MobileBertModuleTest::test_module_static_vulkan
FAILED tank/pytorch/squeezenet1_0/squeezenet1_0_test.py::SqueezenetModuleTest::test_module_dynamic_vulkan
= 9 failed, 25 passed, 6 skipped, 112 deselected, 1 xfailed, 1 xpassed in 270.06s (0:04:30) =
```

**Comment by PhaneeshB** [comment] 2022-08-02 23:20
@stellaraccident 

Command :

```
<PATH TO ..../iree-compile> - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=<PATH TO ..../iree-lld> --mlir-print-debuginfo --mlir-print-op-on-diagnostic=true --iree-llvm-target-cpu-features=host -iree-vulkan-target-triple=m1-moltenvk-macos --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-flow-demote-f64-to-f32=false%
```

MLIR : `https://storage.googleapis.com/shark_tank/squeezenet1_0/squeezenet1_0_torch.mlir`

**Comment by antiagainst** [comment] 2022-08-04 18:38
What input should I use? With `tools/iree-run-module --device=vulkan --module_file=squeezenet-vulkan.vmfb --entry_function=forward --function_input=1x3x224x224xf32` on 36f2451913c025c725f2d7e03935d2e9da9a872c I cannot reproduce this. Results are not NaN.

**Comment by PhaneeshB** [comment] 2022-08-11 11:28
@antiagainst 
I've tried reproducing the issue on my end, it is always reproduced when using pytest command to run test
but, w/o pytest (simple python script for test) and using iree-compile + iree-run-module I'm unable to reproduce the issue. 

Also, this failure is specific to Vulkan, CPU test always pass
Not unsure on how to debug this further, lmk if you've got any ideas

**Comment by azhenone** [comment] 2022-09-05 09:03
There is something you should definitely check : the dimensions of the input image

I tried to train that network on a Nvidia GetForce GPU with images of CxHxW dimensions 3 x 160 x 512 and it kept producing NaN. The weirdest thing is that I did not have that issue when training on CPU. So I decided to reduce the image sizes to 3 x 160 x 256 and it stop producing NaN.

This may require more experimentation but the conclusion I can draw from that test is that there might be an implicit max sizes that the model expected to function "normaly"

**Comment by antiagainst** [comment] 2023-06-24 00:16
Closing this for now given this is Vulkan on MoltenVK -- we have native Metal support and that's the way forward.

**Closed by antiagainst** 2023-06-24 00:16 UTC
Labels: bug 🐞, platform/macos 🍎, codegen/spirv
